[package]
name = "passerine"
version = "0.6.0"
authors = ["Isaac Cayton (slightknack) <slightknack@gmail.com>"]
edition = "2018"
description = "A small extensible programming language designed for concise expression with little code."
license = "MIT"
license-file = "LICENSE.txt"
readme = "README.md"
repository = "https://github.com/passerine-lang/passerine"
