[package]
name = "passerine"
version = "0.8.0"
authors = [
    "Isaac Clayton (slightknack) <slightknack@gmail.com>",
    "The Passerine Community",
]
edition = "2018"
description = "A small extensible functional scripting language designed for concise expression with little code."
license = "MIT"
readme = "README.md"
repository = "https://github.com/vrtbl/passerine"
