[package]
name = "passerine"
version = "0.4.2"
authors = ["Isaac Cayton (slightknack) <slightknack@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# NOTE: I'm trying to keep passerine a no-deps library
[dependencies]
