[package]
name = "passerine-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# I would put this under dev-dependencies if I could.
proptest-derive = "0.3.0"
proptest = "1.0.0"